### ISSUE TITLE
skel + wordpress = function.php

### ISSUE THREAD

**Issue by densityx** [n33/skel#100]
#98 

How do we use it in the functon.php ...
``` <script>window._templateDirectory = '<?php echo get_template_directory_uri(); ?>';</script> ```
where do we use these code?
```
function load_style_and_scripts(){
	wp_register_script( 'skel', 'window._templateDirectory = <?php echo get_template_directory_uri(); ?>' . '/js/skel.min.js' , array(jquery) );
	wp_register_script( 'init', get_template_directory_uri() . '/js/init.js' , array(skel) );

	wp_enqueue_script( 'skel' );
	wp_enqueue_script( 'init' );

}

add_action( 'wp_enqueue_scripts', 'load_style_and_scripts' );
```

how do we use it?..

**Comment by CliffObvious** [comment]
Hi - this seems to work a treat - the breakpoints come in where expected.... BUT - I'm still having problems when it gets to mobile, the images don't scale down & - if anything - get bigger! 

I've tried going 'back to basics' - downloading a clean version of the theme from HTML5UP & converting that to WP. 
I've done nothing to it other than carving it up to the required WP files, & converting the css / js pulls to the above example... Works fine apart from - as I say - this issue as it gets to mobile. 

I'm going to start tinkering again, but if anyone out there has any ideas, would be great!

**Comment by CliffObvious** [comment]
WAIT - I think I've got it... I was loading the css files from the functions.php file. Logic was that they'd need to be loaded via functions for init to call upon them. Seems that's not the case. 

For anyone else struggling with this problem - so long as the header is running

<script>window._templateDirectory = '<?php echo get_template_directory_uri(); ?>';</script>

and the init file has been edited so the filenames run as per;
href: window._templateDirectory + '/css/style.css'

Then the functions just needs to call in the JS files & the code densityx listed above. 

My functions.php file is currently showing the following... 

//IMPORT CUSTOM JS FILES// 
function theme_js (){
	wp_enqueue_script( 'html5shiv_js', get_stylesheet_directory_uri() . '/js/html5shiv.js' );
	wp_enqueue_script( 'jquerymin_js', get_stylesheet_directory_uri() . '/js/jquery.min.js' );
	wp_enqueue_script( 'skel_min_js', get_stylesheet_directory_uri() . '/js/skel.min.js' );
	wp_enqueue_script( 'skel_layers_min_js', get_stylesheet_directory_uri() . '/js/skel-layers.min.js' );
	wp_enqueue_script( 'init_js', get_stylesheet_directory_uri() . '/js/init.js' );
}

add_action( 'wp_enqueue_scripts', 'theme_js' );
//END IMPORT CUSTOM JS FILES// 

//IMPORT SKEL FRAMEWORK // 
function load_style_and_scripts(){
    wp_register_script( 'skel', 'window._templateDirectory = <?php echo get_template_directory_uri(); ?>' . 'js/skel.min.js' , array(jquery) );
    wp_register_script( 'init', get_template_directory_uri() . 'js/init.js' , array(skel) );

    wp_enqueue_script( 'skel' );
    wp_enqueue_script( 'init' );

}

add_action( 'wp_enqueue_scripts', 'load_style_and_scripts' );
//END IMPORT SKEL FRAMEWORK // 


I've spent weeks struggling over this final detail, so hope this little extra helps people.

**Comment by n33** [comment]
:+1:  Thanks for digging into this. I'm sure it'll be a big help to someone else.
