### ISSUE TITLE
No Viewport Triggered

### ISSUE THREAD

**Issue by anthonyabraira** [n33/skel#104]
Not sure why but why but my configuration:

skel.init({
		reset: 'normalize',
		breakpoints: {

			// Global.
				global: {
					href: window._templateDirectory + '/_/inc/css/baseline/style.css',
					containers: 920,							
					grid: {
						gutters: ['1.25em', '1.5em'],
					}
				},
			
			// XLarge.
				xlarge: {
					media: '(max-width: 1280px)',
					href: window._templateDirectory + '/_/inc/css/baseline/style-xlarge.css',
					containers: 900,
				},
				
is not generating any viewport meta tags.

This is how the header loads (pardon its in Wordpress): 

<head id="<?php echo of_get_option('meta_headid'); ?>" data-template-set="html5-reset-wordpress-theme">

	<meta charset="<?php bloginfo('charset'); ?>">

	
	

	<?php if (is_search())
	echo '<meta name="robots" content="noindex, nofollow" />'; ?>

	<title><?php wp_title( '|', true, 'right' ); ?></title>
	<meta name="title" content="<?php wp_title( '|', true, 'right' ); ?>">
	<meta name="description" content="<?php bloginfo('description'); ?>" />

	<?php
		if (true == of_get_option('meta_author'))
			echo '<meta name="author" content="' . of_get_option("meta_author") . '" />';

		if (true == of_get_option('meta_google'))
			echo '<meta name="google-site-verification" content="' . of_get_option("meta_google") . '" />';
	?>

	<meta name="Copyright" content="Copyright &copy; <?php bloginfo('name'); ?> <?php echo date('Y'); ?>. All Rights Reserved.">

	<?php

		if (true == of_get_option('head_favicon')) {
			echo '<meta name=”mobile-web-app-capable” content=”yes”>';
			echo '<link rel="shortcut icon" sizes=”1024x1024” href="' . of_get_option("head_favicon") . '" />';
		}

		if (true == of_get_option('head_apple_touch_icon'))
			echo '<link rel="apple-touch-icon" href="' . of_get_option("head_apple_touch_icon") . '">';
	?>
	
	

	<script src="<?php echo get_template_directory_uri(); ?>/_/js/modernizr-2.8.0.dev.js"></script>
	<link rel="profile" href="http://gmpg.org/xfn/11" />
	<link rel="pingback" href="<?php bloginfo('pingback_url'); ?>" />
	
	<?php wp_head(); ?>
	
	<noscript>
	<link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/_/inc/css/baseline/skel.css" />
	</noscript>
	
	<script>window._templateDirectory = '<?php echo get_template_directory_uri(); ?>';</script>
	<?php
	// echo '<script>window._templateDirectory = ' . get_template_directory_uri() . '</script>';
	echo '<script src="' . get_template_directory_uri() . '/_/js/skel.min.js"></script>';
	echo '<script src="' . get_template_directory_uri() . '/_/js/skel.init.js"></script>';
	?>
	<link rel="stylesheet" href="<?php echo get_stylesheet_uri(); ?>" />
	

</head>

You can check out: danieljclancy.com (and see how it doesn't generate them)

**Comment by n33** [comment]
So you're not seeing any <meta> tags even in the browser's inspector? Are you getting any console errors?

**Comment by n33** [comment]
Can't seem to reproduce this so it might be something else. Drop me an email if you still need help.
