### ISSUE TITLE
turbolinks support

### ISSUE THREAD

**Issue by Danpiel** [n33/skel#106]
Hello, I'm developing application with http://html5up.net/alpha template, skel is awesome but I want to use rails-turbolinks (https://github.com/rails/turbolinks) for application. Is there any way to fire skel events after page is loaded by turbolinks ?

Thank you.

**Comment by n33** [comment]
I think combining Skel's `trigger` method (to manually trigger an event) with Turbolinks' own events /might/ do the trick:

```js
$(document).on('page:load', function() {
  // Trigger Skel's "resize" event.
    skel.trigger('resize');
});
```

**Comment by Danpiel** [comment]
Thanks a lot, in dev environment works fine, will see how it goes in production.

**Comment by n33** [comment]
:+1:

**Comment by Danpiel** [comment]
Checked on production environment, skel forces full page reload so combination with turbolinks is useless, also rails assets pipeline not fully usable because of skel's loading styles for different devices.

To get skel working with pipeline, set ```config.assets.compile = true``` and use http caching for faster delivery.

**Comment by n33** [comment]
Hmm, are you using Layers (and the links within a layer are what you're working with)?

**Comment by Danpiel** [comment]
Yes, layers is used for navbar

**Comment by n33** [comment]
Try giving the anchor tags within the layer the `skel-layers-ignore` class. Does that do anything?
