### ISSUE TITLE
skel.on('change') doesn't work in WP

### ISSUE THREAD

**Issue by redanser** [n33/skel#107]
I setup Skel on a simple page and it works just fine. I can ask to alert something like this:

skel.on('change', function() {
  alert('Breakpoint state changed!');
});

When I load the exact same script into my WP-blog (with the wp_enqueue_scripts action), it works fine regarding changing the layout with every breakpoint (so it works, it finds the script and the css and so on), but the function

skel.on('change', function() {
  alert('Breakpoint state changed!');
});

does nothing, nothing gets alerted (yet it does change, as the layout changes, so I know the skel script works and detects changes). I need to change some dynamically set heights when the breakpoints change, so I do feel like I need that event :-/

Any idea on what this is and how I can get it to work?

**Comment by n33** [comment]
Is the script containing that code being loaded after skel.min.js?

**Comment by redanser** [comment]
Yes

**Comment by n33** [comment]
Any console errors?

**Comment by redanser** [comment]
TypeError: skel.on is not a function

skel.on('change', function() {

I'm probably making a big mistake (not a jQuery specialist, to say the least...), but it does not give the same error when I use the exact same file in a non-WP site, and then it alerts just fine :/

**Comment by n33** [comment]
Yeah, sounds like Skel's being loaded after your script (which means the
`skel` object won't exist in time for your `on()` call).

**Comment by redanser** [comment]
But the call is in the last file in this list (taken from the page source, so WP loads it like this):

<script type='text/javascript' src='http://localhost/rare/wordpress/wp-includes/js/jquery/jquery.js?ver=1.11.1'></script>
<script type='text/javascript' src='http://localhost/rare/wordpress/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.2.1'></script>
<script type='text/javascript' src='http://localhost/rare/wordpress/wp-content/themes/rare/js/skel.min.js?ver=4.1'></script>
<script type='text/javascript' src='http://localhost/rare/wordpress/wp-content/themes/rare/js/skel-layers.min.js?ver=4.1'></script>
<script type='text/javascript' src='http://localhost/rare/wordpress/wp-content/themes/rare/js/jquery.bxslider.min.js?ver=4.1'></script>
<script type='text/javascript' src='http://localhost/rare/wordpress/wp-content/themes/rare/js/init.js?ver=4.1'></script>

**Comment by redanser** [comment]
I put this code in my functions-file: 

	wp_enqueue_script(
		'init',
		get_stylesheet_directory_uri() . '/js/init.js',
		array( 'jquery','skel' )
	);
so I even explicitly tell WP that it depends on skel :/

**Comment by redanser** [comment]
And if I ask to do something if skel is an object, one line before I put the 'change'-code part, it does that, so skel is an object at that time :/

**Comment by n33** [comment]
Weird! Think you can put this somewhere online so I can check it out? You can email me the URL if you don't want it public (aj@n33.co).

**Comment by redanser** [comment]
Sure, I'm just setting it up now, but it should get online somewhere in the next days. Thanks in advance!

**Comment by n33** [comment]
Closing since this isn't a Skel issue (but rather an implementation one). Feel free to email me when you get your stuff online though.
