### ISSUE TITLE
init.js wont load css files in WP

### ISSUE THREAD

**Issue by beestenbrein** [n33/skel#109]
Not sure why, but init.js isnt loading the css files, so my site wont react to diffirent window sizes.

I added the script tag: 
```<script>window._templateDirectory = '<?php echo get_template_directory_uri(); ?>';</script>```

and changed the hrefs in init.js to 
```href: window._templateDirectory + '/css/style.css'```

as you explained here:
https://github.com/n33/skel/issues/98#issuecomment-64813526

But still no luck! Is there anything else i can try?

**Comment by n33** [comment]
Closing since this isn't directly related to Skel, but email me if you'd like to pick this up there.
