### ISSUE TITLE
Including css files question, page flicker issue

### ISSUE THREAD

**Issue by djensen47** [n33/skel#110]
I'm using on of the HTML5Up templates for a website, which (as you know) uses skel. I was experiencing a brief flicker of un-styled raw page content before the page rendered properly. I've also seen this happen on the skel doc pages.

To fix it I moved the noscript css out of the noscript tag and the flicker is gone.

1. Is this an acceptable solution to the problem?
2. It seems like loading CSS via JavaScript is an anti-pattern? If you disagree, what is the rationale? Just curious, thanks.

**Comment by n33** [comment]
What you're describing (FOUC) hasn't shown up in my own testing, but I know in some circumstances does (eg. doing anything that actively monitors the DOM, like using Firebug). Sooo....

1. Shouldn't be a problem, although my solution below's a bit better.

2. Basically it's a way to consolidate the media queries in one place (more info here: http://getskel.com/docs#breakpoint-manager-usage-consolidation). Entirely optional of course, so if you'd prefer to not do things this way, remove the `html` option from each breakpoint in js/init.js, remove the style.css `<link>` tag from your `<noscript>` block, and then either:

a) Set up `<link>` tags for each breakpoint's stylesheet (using the `media` attribute).

-or-

b) Merge each breakpoint's stylesheet into style.css (using the `@media` directive).

**Comment by djensen47** [comment]
Thanks for the tip.

Create a Windows VM with limited resources and you'll should easily be able to reproduce the flicker issue.

**Comment by n33** [comment]
Gotcha. Will do.
