### ISSUE TITLE
SideBar Problem

### ISSUE THREAD

**Issue by alexiscote** [n33/skel#111]
I am making a ASP.NET website using skel. On mobile, when my sidebar resize, my button's javascript stop working. On full wide it works but on mobile it doesn't. Any hint on what could be the issue ?
I'm also using skel-layer.

Init.js file : http://pastebin.com/y7YaRZtj

Thanks!

**Comment by n33** [comment]
Probably an issue with the template you're using / Layers, so I'm closing this here but feel free to email me directly about it.
