### ISSUE TITLE
Totally Cool!!

### ISSUE THREAD

**Issue by lance1572** [n33/skel#112]
I wish there was a place to comment on how great this piece of work is!!! So I will do it here. 
Thank you for the enormous work you have done!!! This has streamlined my workflow in such a way that it has given me such HIGH stoke! Other than getting used to porting in a couple different style sheets based on screen-size setting this up was basically a no-brainer! thanks!!! I will use this from now on as my go-to!

**Comment by n33** [comment]
Haha, thanks :) Glad you dig it :+1:
