### ISSUE TITLE
Breakpoint triggered too late on Windows Phone

### ISSUE THREAD

**Issue by morvy** [n33/skel#114]
I'm trying to solve an issue with WP. I have template based on your baseline, so 6 breakpoints. WP loads with global and only after some movement/pinch it tries to change the size, but it's doing really slowly this transition (about 10 seconds?).

**Comment by n33** [comment]
What version of Windows Phone are you using (and which phone)?

**Comment by morvy** [comment]
Lumia 920 (768x1280),
Windows Phone 8.1 (Cyan update),
OS version: 8.10.14219.341
Core Build ID: 3051.50009.1451.10458

**Comment by n33** [comment]
Can't reproduce this using Baseline on my test device (a Lumia 520, also running 8.1). Is the template in question up somewhere live I can check out?
