### ISSUE TITLE
skel.js and Joomla 3.3 "mobile rules dont work

### ISSUE THREAD

**Issue by gandre82** [n33/skel#116]
Hello there,

i found on the web, the < Big Picture by HTML5 UP Template> 

i like to convert it into a joomla template, but the mobile ability does not work the styles were not assigned as they should. 

for better understanding here are 2 links

this one is the working one (its the pure template without joomla code)
http://www.agdl.de/wide/

and this is my joomla installation width the modified template:
http://www.agdl.de/bcms/

--- if you resize the browser, you see the problem. i don´t know why, but i want to fix this! any suggestions?

greets andre

**Comment by gandre82** [comment]
oh well, thx for your suggestions... 8-| i found a workaround, not nice, but it works... i copied the relevant folders in the joomla root. now the mobile and widelayout works fine. 

but thats not the goal, i heard about a prefix-tag for the path-declaration... how should i use this? greets andre

**Comment by n33** [comment]
Try prefixing each of the `href` values in js/init.js with the correct path to your CSS files.
