### ISSUE TITLE
How to offset by halves

### ISSUE THREAD

**Issue by lance1572** [n33/skel#117]
Hi n33!
I have 5 inner divs (cells) that need to be aligned center within a row. Each div takes on the 2u width. How would one go about offsetting by 1 and half? 

I added something like this to the skel.min,js
+ ".\\-12u" + e + "{margin-left:7.5%}"

Obviously that added 2 isn't correct with naming but I got it to work somewhat. I know its not recommended to edit the source. Do you have a sort of work around you do if you encounter 'issues' like these.

**Comment by n33** [comment]
Not supported at the moment I'm afraid, though that workaround will sort of work until I figure out a better way to handle situations like those.
