### ISSUE TITLE
Google Maps API / Adsense in IE

### ISSUE THREAD

**Issue by gulo101** [n33/skel#118]
Hello,

Hopefully this is the right place for my question.

I am trying to build a webpage by using Skel. My page uses Google Maps API and Adsense. 

For some reason the map is not loading at all in Internet Explorer (I am using version 11) but works fine in Chrome and Firefox. It's only happening once I upload the file to my server (hosted on Godaddy), it does work when I open the html file locally on my PC. 

By stripping away all the code to bare bones I found out that that map will load as long as I remove the script for adsense. It also works fine if I don't load any of the skel.js files. So something between skel / adsense / google maps seems to be clashing in IE.

I uploaded two test files:

1) Has Google map and Adsense scripts - will NOT load map in IE (http://www.cospringstrails.com/NEW/test.html)

2) Has Google map but no Adsense - works fine in IE
(http://www.cospringstrails.com/NEW/test-noad.html)

Can anyone please take a look and help me figure out what's wrong?

thanks

**Comment by gulo101** [comment]
It looks like the issue is with <script src="js/skel-layers.min.js"></script> 

When I remove it from the HTML file both map and adsense load fine...

**Comment by n33** [comment]
Page isn't up anymore, but are you using Baseline? If so, try setting `mode` (in js/init.js) to `position`. In lieu of that, do any errors come up in IE's console?

**Comment by gulo101** [comment]
Hello, 

Well this is weird. I have abandon the project for a while but I just put those 2 test files back up tonight and they both load just fine in IE. So something has changed since then, not sure what - some IE or Google Maps API update perhaps? Either way it doesn't look like it was issue with Skel...thanks

**Comment by n33** [comment]
:+1:
