### ISSUE TITLE
Fixed Titlebar Outside of init.js but inside #skel-layers-visibleWrapper

### ISSUE THREAD

**Issue by buzzguy** [n33/skel#119]
Really smooth off canvas layers action! 
It works nicely, though I wanted to create essentially 2 fixed navs (similar to mashable) where upon scrolling, a second fixed navbar overlays the original with more options with share buttons. I created the nav bars in the html rather than the init.js so I could control the position better, but since it's outside #skel-layers-visibleWrapper, it doesn't stayed fixed after opening the off canvas layer. 
Can I use the off canvas fuctionalities without using the init layers plugins?

**Comment by n33** [comment]
Adding the class `skel-layers-fixed` should get them to play nice. Alternatively, try setting Layers' `mode` option to `position` (rather than `transform`).

**Comment by buzzguy** [comment]
thanks, I'll try it out!
