### ISSUE TITLE
Konqueror Browser (KDE) displays mobile version

### ISSUE THREAD

**Issue by Markus-Go** [n33/skel#120]
Konqueror on Ubuntu LTS (Version 4.13.3) is not recognized as a desktop browser and displays the mobile layout. Using Version 2.2.1of skel.min.js

**Comment by n33** [comment]
Hmm, does this happen with anything using Skel (eg. http://getskel.com/downloads/skel-baseline/ or the stuff at http://html5up.net)?

**Comment by Markus-Go** [comment]
The getskel.com website works fine and fast, everything on html5up.net does not.
Additionally, when accessing html5up.net using konqueror, the website takes about 3-4 minutes to render using 100% of CPU.

The default identification string is 
"Mozilla/5.0 (X11; Linux x86_64) KHTML/4.13.3 (like Gecko) Konqueror/4.13"

**Comment by n33** [comment]
Try updating to the latest version of Konqueror (4.14.3). If that doesn't work, please reopen this over at [github.com/n33/skel.old](http://github.com/n33/skel.old).
