### ISSUE TITLE
z-index

### ISSUE THREAD

**Issue by dabpc** [n33/skel#121]
I'm loving Baseline (http://getskel.com/downloads/skel-baseline/), many thanks.
Having an issue with an image slider, in “responsive” / “mobile view” the z-index value appears to be higher than skel, so the "banner" image shows on top of the slide out navigation. Adding a z-index value to "#navPanel" doesn't seem to make a difference in e.g. "style-medium.css".
Is it hard coded in the js? Any hints hugely appreciated.

**Comment by n33** [comment]
Try increasing Layers' `baseZIndex` option. More info here: http://getskel.com/docs/layers#configuration-reference

**Comment by dabpc** [comment]
Perfect! Thanks for pointing me in the right direction.
