### ISSUE TITLE
What are the reasons behind different usage of Skel in Spectral theme ?

### ISSUE THREAD

**Issue by Madebym** [n33/skel#122]
I've just now downloaded the latest HTML5Up theme, and saw that it is setup a bit differently.
Skel and init scripts are loaded at the bottom, but the part I don't get is why is Skel included in the main stylesheet along with baseline and all the styles.

Also, this part is confusing me. The breakpoints are defined, but how are they used?

    skel
		.breakpoints({
			xlarge:	'(max-width: 1680px)',
			large:	'(max-width: 1280px)',
			medium:	'(max-width: 980px)',
			small:	'(max-width: 736px)',
			xsmall:	'(max-width: 480px)'
		});

**Comment by n33** [comment]
Spectral actually uses a dev version of Skel v3. Not on GitHub yet, but it will be in the coming weeks as it approaches a releasable state.
