### ISSUE TITLE
Priority on cell not working

### ISSUE THREAD

**Issue by joeyvanbilsen** [n33/skel#125]
Hi there,

When I prioritze a cell on content which is loaded to my page by PHP it doesn't get the priority it should.

<div class="8u 12u$(xsmall)"></div>
<div class="4u$ 12u$(xsmall) important(xsmall)"></div>

Any ideas?

Thnx in advance

**Comment by n33** [comment]
What does the output HTML look like?

**Comment by joeyvanbilsen** [comment]
It's loaded through ajax from, let's say my_ajax_request.php, which echos as response into index.html by the following code
```
echo '<div class="content row right">';
    echo '<div class="8u 12u$(xsmall)">';
        echo '<header>';
            echo '<h2></h2>';
            echo '<p></p>';
            echo '<ul class="actions">';
                echo '<li></li>';
                echo '<li></li>';
            echo '</ul>';
        echo '</header>';
    echo '</div>';
    echo '<div class="4u$ 12u$(xsmall) important(xsmall)">';
        echo '<span class="image"></span>';
    echo '</div>';
echo '</div>';

```

The output in index.html:

```
<div class="content row right">
    <div class="8u 12u$(xsmall)">
        <header>
        <h2></h2>
        <p></p>
        <ul class="actions">
            <li></li>
            <li></li>
        </ul>
        </header>
    </div>
    <div class="4u$ 12u$(xsmall) important(xsmall)">
	    <span class="image"></span>
    </div>
</div>
```
The alignment of the cells is working properly, but the priority on the last cell doesn't work. When I try this by just creating the example inside index.html without the use of ajax or php, the priority is working as should.

**Comment by algirdasp** [comment]
Are you possibly using the new Spectral template? I am having the same problem. Spectrak is built on Skel 3.0.0-dev, and it seems like that version does not yet have the important class support.

**Comment by n33** [comment]
Skel only checks for `important` whenever the state (ie. active breakpoints) changes, so when you load in new markup with ajax you won't trigger that behavior. However, you *might* be able to force it by calling the following after your ajax call has succeeded:

```js
skel.applyRowTransforms(skel.vars.state);
```

Does that work?

@algirdasp; Separate issue with Spectral. It's built on a dev version of Skel 3 which (among other things) handles the grid a bit differently. More on that soon.

**Comment by n33** [comment]
Please reopen this over at [github.com/n33/skel.old](http://github.com/n33/skel.old) if it's still an issue.

**Comment by hozza** [comment]
I'm having this same issue (on the new Skel JS). Looks like `important(mobile)` is only triggering when the browser window size is changed rather than when initially loaded, my content is loaded in via AJAX, presumably after Skel as checked for `important()` 

Is there anyway to ask Skel to check again for important? 

`skel.applyRowTransforms(skel.vars.state);` just returns `TypeError: skel.applyRowTransforms is not a function` for me.
