### ISSUE TITLE
Floating doesn't work correctly when blocks have different height

### ISSUE THREAD

**Issue by morvy** [n33/skel#126]
Hi,
I'm using standard **div / row > div / 4u > a / image fit** (with img and span for description). When there are 2 lines of text in description (instead of 1), floating doesn't work correctly. I'm using a workaround with **$** on last row element, but as I'm also using MixItUp, so after filtering blocks, I receive not so nice output (different number of blocks per row).
In ZF 5 it works fine (I think)

**Comment by n33** [comment]
Might be a conflict with MixItUp. Please reopen this over at [github.com/n33/skel.old](http://github.com/n33/skel.old) if it's still an issue.

**Comment by morvy** [comment]
Hi,
that bug has nothing to do with mixitup, because the same behavior is in my
Gallery so I have to terminate each row there

it's here: http://revotechnik.sk/galeria

when you delete some galleries with 2 row title and remove $ from classes,
it will break :)

[image: Vnorený obrázok 1]

Best Regards,
Peter

2015-05-10 23:22 GMT+02:00 aj <notifications@github.com>:
