### ISSUE TITLE
Bold Text <b> / <strong> / etc

### ISSUE THREAD

**Issue by CliffObvious** [n33/skel#127]
HI there, 

I seem to be having issues with setting text to bold within a Skel template. the < b > and < strong > tags don't work, and I've found a workaround by using < span class="bold" > to display text in a bold format. 

Whilst this is fine for design, etc - when it comes to users amending text themselves, we have a problem. The Tiny MCE editor, or Wordpress interfaces I use for clients to go in & edit their own text obviously don't have this workaround as an option for bold text, and telling people to go into the HTML is not really an option either. 

Any ideas why this might be, or pointers on how to change things within the framework to re-instate the bold text tags to working again would be gratefully appreciated. 

Thanks!

**Comment by n33** [comment]
Not a Skel issue, but adding this to your stylesheet will fix it:

```css
i, em { font-style: italic; }
```

**Comment by CliffObvious** [comment]
Hi, 

That doesn't seem to work. I'll admit to being a bit confused, too - how would adding an italic command help the problem with text not appearing in bold?

**Comment by n33** [comment]
Woops, misread that. Do:

```css
b, strong { font-weight: bold; }
```

**Comment by CliffObvious** [comment]
aha! gotcha - thanks. Makes much more sense & works a treat! Thanks loads.
