### ISSUE TITLE
Fixed position with apple devices

### ISSUE THREAD

**Issue by steamsynthetic** [n33/skel#129]
I have an issue with apple devices, which have issues supporting fixed position elements. I have added the "skel-panels-fixed" class to the header element, and added "position: fixed, top: 0px" in css. However,  because of how ipads/iphones scroll, it still scrolls passed the element. You can take a peek at the dev ip address of the site and feedback as needed. 
http://54.68.240.35/

Note: styling for smaller devices (iphones etc) hasn't been done yet, so an ipad is needed. Also, ipad emulation through chrome does not replicate this data. I am testing it on an ipad3. 

I appreciate any help, the framework is excellent.

**Comment by steamsynthetic** [comment]
Nevermind. Fixed with skel layers plugin.

**Comment by n33** [comment]
:+1:
