### ISSUE TITLE
no css file in dist anymore?

### ISSUE THREAD

**Issue by PeterDaveHello** [n33/skel#131]
I see only scss @@

**Comment by n33** [comment]
For now no, though that may change. How were you using it before?

**Comment by PeterDaveHello** [comment]
No, just want to make sure the link on cdn (https://cdnjs.cloudflare.com/ajax/libs/skel/2.2.1/skel.min.css) still work after changing its version number, what do you think?

**Comment by n33** [comment]
Ah. If you can redirect that particular version to a different repo, point it here: https://github.com/n33/skel.old/blob/master/dist/skel.css

**Comment by PeterDaveHello** [comment]
What do you mean @n33 ? Old versions will still be here : https://cdnjs.com/libraries/skel
We just want to keep the structure as before, I noticed that there is scss in dist, so do you want user to build css by their own?

**Comment by n33** [comment]
Yep. Actually, now that I think about it skel.css shouldn't have been on a CDN to begin with (since it's meant to be edited, not used as-is).

**Comment by PeterDaveHello** [comment]
okay, sure, I got it!
