### ISSUE TITLE
html5 video doesn't work (Chrome only) 

### ISSUE THREAD

**Issue by Nndo** [n33/skel#132]
Hi, 

I'm working on a wordpress theme integrated with skel and skel-layers. 
Now i'm trying to install an html5 video background  (using classic <video> tag / no js)  but it won't work in Chrome. 
Maybe there's something wrong in my init.js file?

(dequeuing skel-layers.js from my function.php file, it works) 

anyway, great framework! 
Thanks a lot for your support!

**Comment by n33** [comment]
Sure. So this pertains to the previous version of Skel (http://github.com/n33/skel.old), but try adding this to your Layers config:

```js
mode: 'position'
```

If it's still a problem, reopen this issue over at http://github.com/n33/skel.old

**Comment by Nndo** [comment]
I'm sorry but still have this problem..

https://github.com/n33/skel.old/issues/1

thank you
