### ISSUE TITLE
Ipad issue

### ISSUE THREAD

**Issue by steamsynthetic** [n33/skel#133]
I had an issue with ipad before, and went back through and got the code working correctly. However, I am noticing one small issue. This is still related to Ipad usage / Safari. Chrome doesn't load at all on an ipad for some reason.

When I scroll down the page, everything works fine. When I scroll back up, everything works again... However if I go back down the page a second time with out reloading, nothing fires any longer. Sometimes it doesn't even take that long. Moving around the page, it seems that somewhere things will hang and no longer trigger to show content. 

Here's the dev IP. If you need any other files, let me know.
http://54.68.240.35/

**Comment by n33** [comment]
Please reopen over at https://github.com/n33/skel.old. Thanks!
