### ISSUE TITLE
important(breakpoint) not being prioritised for Ajax content

### ISSUE THREAD

**Issue by meiso** [n33/skel#135]
Hi,
I've been using the (brilliant) skel.js for a project, and it's been humming along smoothly until this one issue. We use an ajax function to pull content into the page; skel happily processes this, apart from for one cell with the important() class attached. This is ignored and treated as if it were a normal, non-important unit.

As soon as there is a state change, orientation change etc it picks up the important() cell and plops it to the top. I've tried manually trigger a changeState after our ajax pull by trying things like skel.changeState(skel.getStateId()); but that doesn't work. Is there a workaround for this, or a way I can manually tell Skel to reapply \ recheck its breakpoints? skel.poll won't work as there hasn't been a state change.

Many thanks in advance!

**Comment by meiso** [comment]
Gah, sorry, found a workaround now. skel.changeState(skel.getStateId()); does work, it was just an error on our implementation (it wasn't being called until the ajax had completely finished posting\updating, instead it was just being called straight after the ajax function was called).

Nonetheless, the pre-workaround important() issue seems to still be there. 

Thanks again for skel! :)

**Comment by n33** [comment]
:+1:
