### ISSUE TITLE
What happened to the website??

### ISSUE THREAD

**Issue by TLMcode** [n33/skel#138]
I hope the site isn't gone. I often use baseline and layers live documentation as a guideline for my skel projects. Please point me in the right direction. Thanks

**Comment by ramsey** [comment]
I still use Skel 2.x for my website and some projects, and I agree that the old documentation (at least in downloadable archive form) would be great to have.

**Comment by n33** [comment]
Doh, my bad. I forgot to mention I added PDF versions of the Skel 2 docs a few days ago: https://github.com/n33/skel.old/tree/master/docs
