### ISSUE TITLE
Refreh layer

### ISSUE THREAD

**Issue by RichardKBR** [n33/skel#141]
First thank you! (skell 2 baseline sample)

I have some issue when a do a ajax post and update an element in <header class="skel-layers-fixed">, 
the element doesn't refresh, only on F5. 
When debug i can see, the element has sucessfully updated in code, but in screen doesn't.
I try several approaches like (selector is parent div of <header class="skel-layers-fixed"> and button is inside skel-layers-fixed):
        $("#mydiv").hide()
        $('#mydiv').get(0).offsetHeight;
        $("#mydiv").show(0);

        $("#mydiv").height($("#selector").height() - 1);
        $("#mydiv").height($("#selector").height() + 1);

        $("#mydiv #mybutton").fadeTo(100, 0.1).fadeTo(200, 1.0);
        
        $("#mydiv #mybutton a").css('background-color', '').css('background-color', 'red');
        var z = $("#mydiv #mybutton a");
        var y = $("#mydiv #mybutton a").parent();
        $("#mydiv #mybutton a").remove();
        y.append(z);

None of this approaches worked. 
PS.: when i resize page to a small width, to "mobile version", work but when resize again the element still incorrect.

(Sorry for my English, i speak Portuguese)

**Comment by n33** [comment]
Hey, please reopen this over at http://github.com/n33/skel.old
