### ISSUE TITLE
Firefox android mobile layout not applied

### ISSUE THREAD

**Issue by ldrolez** [n33/skel#143]
I use a template from html5up.net (based on skel3), and most of the time, with Android Firefox, the desktop version of the site is shown. If I force a reload, the mobile version is shown. How could I debug this?

**Comment by n33** [comment]
Which one are you using?

**Comment by ldrolez** [comment]
halcyonic, the new version with skel3

**Comment by n33** [comment]
Sounds like a browser bug unfortunately. Skel.scss (which is what that template is using) relies on @media so if that's not working (or it is, but unpredictably) it's likely an issue with the way FF is handling media queries.

**Comment by ldrolez** [comment]
Could you suggest a few JS lines that I could insert in the template, to demonstrate what's going wrong with firefox?
