### ISSUE TITLE
Events & Breakpoints

### ISSUE THREAD

**Issue by vebam** [n33/skel#145]
Hello, I have a problem
I would like to alert only for medium Breakpoints
My script looks like this:

	skel.on("+medium", function() {
		alert("Breakpoints");
	});

But, when I check:

		xlarge:  alert does not display
		large: alert does not display
		medium: alert display
		small: alert display
		xsmall: alert display

I understand that I have to define myself media query ?
please help

**Comment by n33** [comment]
Yep. Have you defined any breakpoints using `skel.breakpoints()`?
