### ISSUE TITLE
CSS class names for breakpoints don't jive with Wordpress menus

### ISSUE THREAD

**Issue by anthonyabraira** [n33/skel#151]
I am having the damnest time in applying breakpoint class names for the links in the menus feature of Wordpress. Essentially the problem is that it doesn't support paranthesis {e.g. 4u(medium) }. The output comes out as "4umedium. I was wondering if you had a means to get the breakpoints to be more CSS compliant. Naming structure like 4u--medium or something like that.

**Comment by n33** [comment]
If you're using Skel.scss you can definitely do this with a few tweaks to _skel.scss, but I currently don't plan on changing Skel's default naming conventions (though I may add an "alternate" mode of some kind).
