### ISSUE TITLE
Prioritizing a Cell is not working

### ISSUE THREAD

**Issue by hunbubu** [n33/skel#152]
First of all thanks for making such a great framework like Skel. I've alerady used it in some projects.
Now I would need to prioritizing a cell but it's not working at all. I am using the latest version. I've tried it in Baseline too, but adding important(breakpointName) does nothing.

**Comment by n33** [comment]
Are you using the Layout (JS) module or just Skel.scss?

**Comment by hunbubu** [comment]
In my project I am using only the JS layout, the CSS version is not
implemented yet (Later the CSS version would be included in a <noscript>
element). But it's not working to me on Baseline too.

2015-09-20 4:24 GMT+02:00 aj <notifications@github.com>:

**Comment by edu27** [comment]
I've found a workaround for important:

Editing the skel-layout.js on line 165 just type this: if(config != null)

// Responsive level?
if(config != null)
if (cell.className.match(/important\((.+)\)/) && (l = parseInt(__.gridLevelMap.v[RegExp.$1])) <= config.grid.level)
mode = 'l';

This is my init configuration:
		skel.breakpoints({
			xlarge:	'(max-width: 1680px)',
			large:	'(max-width: 1280px)',
			medium:	'(max-width: 980px)',
			small:	'(max-width: 736px)',
			xsmall:	'(max-width: 480px)'
		});
		
		skel.layout({
		    grid: true,
		    containers: true
		});

Doing this, _.on('change', function() is fired twice, but it is the only way I have working important.

**Comment by smakinson** [comment]
I am seeing the same trouble, but the mentioned workaround seems to fix it. @edu27 Did you find any problematic downside to the _on('change') firing twice?

**Comment by edu27** [comment]
Hi @smakinson,
First of all sorry for the delay.
It's works ok.
