### ISSUE TITLE
invalid selector after 25 on line 221 at column 19

### ISSUE THREAD

**Issue by webbay** [n33/skel#154]
When try to compile _skel.sccs, there is an error: invalid selector after 25 on line 221 at column 19

**Comment by escalate** [comment]
I have the same error while trying to compile the file with node-sass.

**Comment by n33** [comment]
Make sure you're compiling with the latest version of Ruby Sass. If you're using something based on libsass, see #142 (tl;dr = it's a bug; will be fixed in next release of libsass).
