### ISSUE TITLE
gulp-sass compiler error

### ISSUE THREAD

**Issue by tzs007** [n33/skel#155]
[11:28:17] gulp-notify: [Error running Gulp] wp/wp-content/themes/ofiquiz/assets/sass/libs/_skel.scss
  221:28  invalid selector after 25

Runs into an error when I compile skel with gulp.

**Comment by webbay** [comment]
Use gulp-ruby-sass instead of gulp-sass. Detailed answer - https://github.com/n33/skel/issues/142.

**Comment by n33** [comment]
Yup, what @webbay said :)
