### ISSUE TITLE
Console Error: too much recursion

### ISSUE THREAD

**Issue by lance1572** [n33/skel#158]
Hi aj!! Im getting this error in FF. Not sure what to make of it.

too much recursion
`	
...ts[a].push(n)}),t},trigger:function(e){return t.events[e]&&0!=t.events[e].length...
`

For Chrome I am getting

Uncaught RangeError: Maximum call stack size exceeded

Here the html

```
<script type="text/javascript" src="assets/js/skel.min.js"></script>
	<script type="text/javascript" src="assets/js/skel-layout.min.js"></script>
	
<script>
		skel.init({

  reset: 'normalize',
  containers: '95%',
  breakpoints: {
    medium: {
      media: '(min-width: 769px) and (max-width: 1024px)'
    },
    small: {
      media: '(max-width: 768px)'
    }
  }
});
	</script>

	</head>
	<body>
		
		<header>
			<div class="masthead">
				<div class="container">
					<div class="6u">Interior</div>
				</div>
			</div>
		</header>
		<div class="page-wrapper">
			<main>
				<div class="container">
					
				</div>
			</main>
		<footer></footer>
	</div>
	
</body>
</html>

```

**Comment by n33** [comment]
Did you upgrade from a previous version? Skel 3's syntax (particularly the layout stuff) is slightly different:

https://github.com/n33/skel/blob/master/docs/skel-layout.md

**Comment by lance1572** [comment]
I was using init when it should of been layout. Sorry about that. I didnt look at the docs here but locally through textedit. Totally missed it.
