### ISSUE TITLE
Failed to import skell

### ISSUE THREAD

**Issue by nWidart** [n33/skel#160]
Hello,

I just updated to latest version of Skell. And I see a lot has changed , and thus breaking things.

I wanted to include the skell.scss, by using as documented: `@import "skel";` , which after running gulp, returns:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: resources/sass/style.scss
Error: File to import not found or unreadable: skel
       Parent style sheet: stdin
        on line 1 of stdin
>> @import "skel";
   ^

    at options.error (/Users/nicolaswidart/Sites/Asguard/presentation-site/Themes/Alpha/node_modules/node-sass/lib/index.js:277:32)

```

Did I miss something ?

Thanks

**Comment by n33** [comment]
Hard to say. Make sure you're using the latest versions of everything (libsass <3.3 didn't work with Skel.scss) and that _skel.scss is in the right place.
