### ISSUE TITLE
is it possible to set background image conditionally?

### ISSUE THREAD

**Issue by KrishnaPG** [n33/skel#163]
Presently I have a css rule that looks like below:
````
	#banner {
		padding: 16em 0 13em 0;
		background-attachment: fixed;
		background-image: url("images/overlay.png"), url("../images/banner.jpg");
		background-position: center top;
		background-size: cover;
		line-height: 1.75;
		text-align: center;
	}
````
Right now the `background-image` is same irrespective of display size. Is there anyway with skel this can be dynamically configured (so that different sized images get loaded based on the current active breakpoint)?

**Comment by n33** [comment]
Yep, just use a breakpoint. For example, if you're using Skel.scss with a typical set of breakpoints:
```
@include breakpoint(medium) {
    #banner {
        background-image: url("images/overlay.png"), url("../images/banner-medium.jpg");
    }
}
```
