### ISSUE TITLE
Conditionals don't seem to be working

### ISSUE THREAD

**Issue by michaelcummings** [n33/skel#165]
So I've been trying to get the conditionals to work, but I'm not sure if I've got a version that doesn't have conditionals included...

````
skel.layout({
    conditionals: true
});
````

The theme I'm using says "Skel 3*" is what was used.

This is what I'm doing at the moment and its certainly not working:

````
@include skel-layout((
		reset: 'full',
		boxModel: 'border',
		grid: ( gutters: 1.5em ),
		conditionals: true
	));
````

Any idea?

**Comment by n33** [comment]
Skel.scss doesn't support conditionals yet (due to some issues I had getting the `only-` conditionals working correctly with CSS alone). Might have another go at it when I have time to revisit the issue.
