### ISSUE TITLE
skel.min.js Breaks html5 Video

### ISSUE THREAD

**Issue by forestkelley** [n33/skel#166]
skel.min.js is causing html5 video not to load or play correctly. 

I can only find one other comment on the web with this issue: https://github.com/n33/skel/issues/132. n33 says that this pertains to the old version of skel and to try adding mode: 'position' to the Layers Config. I'm not sure how to go about that? Any solutions? 

Here is the version info: /* skel.js vx.x | (c) n33 | n33.co | MIT licensed */

**Comment by n33** [comment]
Moved: https://github.com/n33/skel.old/issues/1
