### ISSUE TITLE
Flicker of unstyled content on Firefox

### ISSUE THREAD

**Issue by pluspurple** [n33/skel#4]
Hi, I get a brief flash of unstyled content at break points on Firefox 23.0.1 (windows 7). I get it on the example on your site, as well as my own site I am building.

Is this a known issue, have you seen it happen before, and what might be causing it?

PS Love the script otherwise!

Thanks

**Comment by mrclay** [comment]
Sounds like the same problem we're having: https://github.com/Elgg/Elgg/issues/8328#issuecomment-103519427
