### ISSUE TITLE
skel-layers?

### ISSUE THREAD

**Issue by stevewithington** [n33/skel#52]
Using the HTML5 UP theme "twenty" and noticed it's using skel-layers.min.js. Is there an unminified version available?

**Comment by Serubin** [comment]
Any updates on the unminified version. Or documentation? It's been difficult to locate either.

**Comment by n33** [comment]
Layers has been deprecated but you can find it here:

https://github.com/n33/skel.old/tree/master/src

**Comment by Serubin** [comment]
Thank you - that's exactly where I found it.
I'm just too lazy to update at the moment.

**Comment by xstable** [comment]
Only open your Chrome-Browser console, go to tab "Sources" ... search the js-File you need and click on the curly brakets { } at the lower left of the data-frame.

So you have an "unminified version" ;)

**Comment by Serubin** [comment]
I've since gotten less lazy and updated :)
