### ISSUE TITLE
Cell 100% height

### ISSUE THREAD

**Issue by skinneejoe** [n33/skel#62]
Please look at these two examples:

http://jsfiddle.net/GBVF8/5/ (with SkelJS)

http://jsfiddle.net/5Br2N/5/ (without SkelJS)

I would like cell heights like shown in the second example but using SkelJS. Basically I want the first and second columns to be vertically aligned in the middle. I want the height to be fluid so it just centers in the middle based on the content inside the tallest div. I don't want to have to set a static height, like 300px. Please advise. Thanks!

**Comment by CristianKrieger** [comment]
Are there any plans for this to be added?

**Comment by n33** [comment]
Probably not at this point, since flexbox will allow you to do this far more elegantly.
