### ISSUE TITLE
Define base path for css?

### ISSUE THREAD

**Issue by JPG-Consulting** [n33/skel#8]
Can I define a base path for the CSS files?

On the main path it works... for example:
http://example.com/index.html

But breaks if I get further up, for example:
http://example.com/products/software.html

Looking in chrome it now tries to load:
http://example.com/products/css/style.css

Can I tell it to stick to: http://example.com/css/style.css ?

**Comment by gandre82** [comment]
Hello folks, 

i have the same problem, my stylesheet and js linkings in the head work well, but my inspector in chrome say: 404 kategorie not found -> the initiator is skel.min.js:2

i read above: that a prefix can fix this, 
but i don´t know, how and where i should insert this(prefix thing) in the init.js.

i hope someone can help me

**Comment by Steve-Parker** [comment]
look at init.js  - use either the prefix command as n33 suggested or alter the href in Global - see an example below...

global: {
				href: '/css/style.css',
				containers: 1400,
				grid: { gutters: ['2em', 0] }
			},
			xlarge: {
				media: '(max-width: 1680px)',
				href: '/css/style-xlarge.css',
				containers: 1200
			},
			large: {
				media: '(max-width: 1280px)',
				href: '/css/style-large.css',
				containers: 960,
				grid: { gutters: ['1.5em', 0] },
				viewport: { scalable: false }
			},

**Comment by juedan** [comment]
Hello,
how to add custom css-files?
Thanks for the answers.

PS: "prefix" does not work.

**Comment by vishwajeetsonkar** [comment]
@JPG-Consulting Can you tell me in detail how you solved it because i also have set the prefix but it is not working for me. it only works for the home page. I am using it with codeigniter so now the path it is looking for is like
http://localhost/ijiimr/index.php/home/templated/css/style.css  

but i want to make it like 
http://localhost/ijiimr/templated/css/style.css 
how do i do this??

**Comment by vishwajeetsonkar** [comment]
@JPG-Consulting  also this link http://skeljs.org/docs#config is not working

**Comment by vkgade** [comment]
In my case, I was getting the exact same error, but the issue was I was loading skel.min.js before init.js, just placing the init.js above skel.min.js, solved the issue.
