### ISSUE TITLE
Wordpress integration issue... with Solution.

### ISSUE THREAD

**Issue by michaelcummings** [n33/skel#84]
I'm trying to play with one of your HTML5 themes and I'm noticing a few things as I try to convert it to a WordPress theme for one of my pet projects.

1.) I'm see you're using a minified version of something called skel-layers.min.js.  I have no idea what this is, and you have no documentation anywhere for it.

2.) skel.js seems to be calling for the stylesheets it needs, but in a WordPress environment this is broken.  It looks for css files relative to the root which wont work inside of a WP theme setting, especially one where you have a staging and production environment. I would suggest that you add that something to documentation somewhere that gives this solution unless you can come up with something better:

Add to your header.php file above your wp_head() call:

``` html
<script type="text/javascript">
var templateUrl = '<?= get_bloginfo("template_url"); ?>';
</script>
```

Then make sure to add that variable to your init.js file like so...

``` javascript
skel.init({
        reset: 'full',
        breakpoints: {
            'global':   { range: '*', href: templateUrl+'/css/style.css' },
            'desktop':  { range: '737-', href: templateUrl+'/css/style-desktop.css', containers: 1200, grid: { gutters: 50 } },
            '1000px':   { range: '737-1200', href: templateUrl+'/css/style-1000px.css', containers: 1000, grid: { gutters: 35 }, viewport: { width: 1080 } },
            'mobile':   { range: '-736', href: templateUrl+'/css/style-mobile.css', containers: '100%', grid: { collapse: true, gutters: 10 }, viewport: { scalable: false } }
        },
....
```

**Comment by rockstarwebdesign** [comment]
AJ, can you please help us integrate skelJS with Wordpress? I can't seem to set it up and worked with Wordpress for over a year integrating Bootstrap and Foundation. I thing Skel is really awesome but if it can't be integrated with Wordpress, it's value drops to almost zero (I think you agree on this.

**Comment by n33** [comment]
Skel works fine with WordPress. See https://github.com/n33/skel/issues/98#issuecomment-64813526.

**Comment by rockstarwebdesign** [comment]
My bad, AJ. Forgot to register the scripts in functions.php. Works fine. Apologies.

**Comment by n33** [comment]
:+1:
