### ISSUE TITLE
prep for automatic CDN uploads

### ISSUE THREAD

**Issue by tomByrer** [n33/skel#86]
I'd like to automate uploads to the [jsDelivr CDN](http://www.jsdelivr.com/) for you (can help with users' browser loading), but I need some help:
- To be clear, you're not using SemVer or other vX.Y.Z versions anymore (you were using 0.4.3, but now just 1.0)?
- The bot needs minified files.  I can set up a Gulp task for you.
- or another option is to upload by hand, which isn't bad if you only release a few times per year.  But it seems you like to fix bugs fast & push out often?

I'll prob set up new folder `skel` instead of the old http://www.jsdelivr.com/#!skeljs

TIA

**Comment by KrishnaPG** [comment]
What is the JSDelivr URL for this?

This one looks different/old: http://www.jsdelivr.com/projects/skeljs
