### ISSUE TITLE
Skel + Wordpress

### ISSUE THREAD

**Issue by Sittus** [n33/skel#98]
The Init.js file takes the entire url , which makes the site only works on the homepage on the other pages the css is not recognized.

Have any simple solution so that I can use skel in my project?

(function($) {

```
skel.init({
    reset: 'full',
    breakpoints: {

        // Global.
            global: {
                href: 'wp-content/themes/codexpress/css/style.css', //works only on the home page, example : contact page - www.mysite.com.br/contato/wp-content/themes/codexpress/css/style.css
                containers: 1400,
                grid: {
                    gutters: ['2em', 0]
                }
            },

        // XLarge.
            xlarge: {
                media: '(max-width: 1680px)',
                href: 'wp-content/themes/codexpress/css/style-xlarge.css',
                containers: 1200
            },

        // Large.
            large: {
                media: '(max-width: 1280px)',
                href: 'wp-content/themes/codexpress/css/style-large.css',
                containers: 960,
                grid: {
                    gutters: ['1.5em', 0]
                },
                viewport: {
                    scalable: false
                }
            },

        // Medium.
            medium: {
                media: '(max-width: 980px)',
                href: 'wp-content/themes/codexpress/css/style-medium.css',
                containers: '90%',
                grid: {
                    zoom: 2
                }
            },

        // Small.
            small: {
                media: '(max-width: 736px)',
                href: 'wp-content/themes/codexpress/css/style-small.css',
                containers: '90%',
                grid: {
                    zoom: 3,
                    gutters: ['1.25em', 0]
                }
            },

        // XSmall.
            xsmall: {
                media: '(max-width: 480px)',
                href: 'wp-content/themes/codexpress/css/style-xsmall.css',
                grid: {
                    zoom: 4
                }
            }

    },
    plugins: {
        layers: {

            // Config.
                config: {
                    transform: true
                },

            // Navigation Panel.
                navPanel: {
                    animation: 'pushX',
                    breakpoints: 'medium',
                    clickToHide: true,
                    height: '100%',
                    hidden: true,
                    html: '<div data-action="moveElement" data-args="nav"></div>',
                    orientation: 'vertical',
                    position: 'top-left',
                    side: 'left',
                    width: 250
                },

            // Navigation Button.
                navButton: {
                    breakpoints: 'medium',
                    height: '4em',
                    html: '<span class="toggle" data-action="toggleLayer" data-args="navPanel"></span>',
                    position: 'top-left',
                    side: 'top',
                    width: '6em'
                }

        }
    }
});

$(function() {

    // jQuery ready stuff.

});
```

})(jQuery);

**Comment by anthonyabraira** [comment]
And the purest sense, I found this article that pertains to using PHP database variables inside of a JavaScript:

https://pippinsplugins.com/use-wp_localize_script-it-is-awesome/

Do you think you can integrate this method into what you already started on this thread?

**Comment by n33** [comment]
This seems a whole lot cleaner. I'll look into it (if for nothing else to mention it in Skel's docs).

**Comment by anthonyabraira** [comment]
I a sorry n33. I should have been a little more specific. Instead of loading the scripts by putting all that on the <head> putting it in the functions.php file. Based off another script that I was able to successfully load on there it looks like this: 

	//* FLUIDBOX
add_action( 'wp_enqueue_scripts', 'enqueue_fluidbox' );
function enqueue_fluidbox() {

	wp_enqueue_style( 'fluidbox-css', get_bloginfo( 'stylesheet_directory' ) . '/_/inc/css/fluidbox.css', array(), CHILD_THEME_VERSION );
	wp_enqueue_script( 'fluidbox', get_bloginfo( 'stylesheet_directory' ) . '/_/inc/js/jquery.fluidbox.min.js', array( 'jquery' ), '1.0.0' );
	wp_enqueue_script( 'fluidbox-init',  get_stylesheet_directory_uri() . '/_/inc/js/fluidbox.init.js', array( 'fluidbox' ), '1.0.0', true );
	}


Now this is what I tried to do on my end in relation to the file locations for skel:

//* SKELJS
	add_action( 'wp_enqueue_scripts', 'enqueue_skeljs' );
function enqueue_slekljs() {

	wp_enqueue_script( 'skeljs', get_bloginfo( 'stylesheet_directory' ) . '/_/js/skel.min.js', false, false, false );
	wp_enqueue_script( 'skeljs-layers', get_bloginfo( 'stylesheet_directory' ) . '/_/js/skel-layers.min.js', false, false, false );
	wp_enqueue_script( 'skeljs-init',  get_stylesheet_directory_uri() . '/_/js/skel.init.js', false , false , false );
	}
		

This isn't working though and I am not sure why.

**Comment by n33** [comment]
Why are you switching between `get_bloginfo` and `get_stylesheet_directory`?

**Comment by anthonyabraira** [comment]
which one would you recommend I stick with? I was deriving this from another tutorial for the integration of fluid box.
